config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"

  resources :items
  resources :orders
  resources :users, only: [:show, :edit, :update, :index]

  namespace :api do
    resources :orders, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :users

  validates :name, presence: true, length: {maximum: 50}
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, presence: true, length: {maximum: 50}

  mount_uploader :photo, PhotoUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items

  validates :user, presence: true

  validates :first_dish, presence: true
  validates :second_dish, presence: true
  validates :drink, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :items

  validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  private

  def set_name
    self.name = "User#{rand(999)}" if self.name.blank?
  end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController

  def index
    orders = Order.all
    render json: orders.to_json(:include => {:user => {
                                              :only => [:email, :name] } },
                                              :only => [:created_at, :first_dish, :second_dish, :drink] )
  end

end


# konata.to_json(:include => { :posts => {
                              #   :include => { :comments => {
                               #                :only => :body } },
                              #   :only => :title } })
  # => {"id": 1, "name": "Konata Izumi", "age": 16,
       # "created_at": "2006/08/01", "awesome": true,
       # "posts": [{"comments": [{"body": "1st post!"}, {"body": "Second!"}],
        #           "title": "Welcome to the weblog"},
         #         {"comments": [{"body": "Don't think too hard"}],
         #          "title": "So I was thinking"}]}


 #<td><%= Item.find(order.first_dish).name %></td>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, notice: I18n.t('controllers.items.created')
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: I18n.t('controllers.items.updated')
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: I18n.t('controllers.items.destroyed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :price, :category, :photo)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show

  end

  # GET /orders/new
  def new

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders


  def create

    @order = Order.new(order_params)
    @order.user = current_user


    if @order.save
      redirect_to items_url,  notice: I18n.t('controllers.orders.created')
    else
      redirect_to items_url, notice: I18n.t('controllers.orders.error')
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:first_dish, :second_dish, :drink)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: I18n.t('controllers.users.created')
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name, placeholder: 'название блюда' %>
  <%= f.input :category, collection: [ "Первое", "Второе", "Напиток"] %>
  <%= f.file_field :photo, label: "Загрузить фото" %>
  <%= f.input :price, placeholder: 'cтоимость' %>
  <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
  или <%= link_to 'вернуться', :back %>
<% end %>

app/views/items/edit.html.erb
<% if current_user == User.first %>

  <h1>Редактирование блюда</h1>
  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>

<% else %>
  <p>Здесь может шариться только Admin</p>
<% end %>

app/views/items/new.html.erb
<h1>Новое блюдо</h1>

<div class="row">
  <div class="col-md-6">
    <% if current_user == User.first %>
      <%= render 'form' %>
    <% else %>
      <p>Что здесь забыл обычный пользователь? Здесь может шариться только админ</p>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% if current_user == User.first %>
  <h1>Блюдо "<%= @item.name %>"</h1>

  <div class="row">
    <div class="col-md-12 buffer-top">
      <div class="row buffer-top">
        <table class="table table-striped">
          <tr>
            <td><b>ID</b></td>
            <td><b>Категория</b></td>
            <td><b>Название</b></td>
            <td><b>Стоимость</b></td>
            <td><b>Управление</b></td>
          </tr>
          <tr>
            <td><%= @item.id %></td>
            <td><%= @item.category %></td>
            <td><%= @item.name %></td>
            <td><%= @item.price %></td>
            <td>
              <%= link_to fa_icon('pencil'), edit_item_path(@item), :title => 'Редактировать' %>&nbsp;
              <%= link_to(fa_icon('trash'), @item, method: :delete, data:
                { confirm: t('are_you_sure') }, :title => 'Удалить' ) %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <%= link_to 'Вернуться', items_path, class: 'btn btn-primary' %>

<% else %>
  <p>Здесь может шариться только Admin</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ланч" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user == User.first %>
              <li><%= link_to 'Заказы', orders_path %></li>
              <li><%= link_to 'Пользователи', users_path %></li>
              <li><%= link_to 'Добавить товар на сегодня', new_item_path %></li>
              <li><%= link_to 'Профиль', current_user %></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
            <% elsif user_signed_in? %>
              <li><%= link_to 'Профиль', current_user %></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Войти', new_user_session_path %></li>
              <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div>
      </div>

      <footer>
        <%= link_to fa_icon('github'), 'https://github.com/alexsevv/',
          :title => 'Разработчик - профиль на Github', target: '_blank', class: 'fa-2x' %>
      </footer>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order, html: { class: 'form-horizontal' }) do |f| %>


  <%= f.input :first_dish, as: :radio_buttons %>
  <%= f.button :submit, 'Отправить', class: 'btn btn-primary' %>
<% end %>

app/views/orders/index.html.erb
<% if current_user == User.first %>
  <h1>Заказы</h1>

  <div class="row">
    <div class="col-md-12 buffer-top">
      <table class="table table-striped">
        <tr>
          <td><b>ID</b></td>
          <td><b>Пользователь</b></td>
          <td><b>Дата заказа</b></td>
          <td><b>Первое</b></td>
          <td><b>Второе</b></td>
          <td><b>Напиток</b></td>
          <td><b>Общая сумма заказа</b></td>
        </tr>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td><%= order.user.name %></td>
            <td><%= l order.created_at, format: :long %></td>
            <td><%= Item.find(order.first_dish).name %></td>
            <td><%= Item.find(order.second_dish).name %></td>
            <td><%= Item.find(order.drink).name %></td>
            <td><%= Item.find(order.first_dish).price + Item.find(order.second_dish).price + Item.find(order.drink).price %> руб.</td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% else %>
  <p>Здесь может шариться только Admin</p>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :name, placeholder: 'имя' %>
  <%= f.input :email, placeholder: 'почтовый ящик' %>
  <div class="buffer-both">
  <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if current_user == @user || current_user == User.first %>
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form', user: @user %>
  </div>
</div>
<% else %>
  <p>У Вас нет права здесь находится</p>
<% end %>

app/views/users/index.html.erb
<% if current_user == User.first %>
  <h1>Пользователи</h1>
  <div class="row">
    <div class="col-md-12 buffer-top">
        <div class="row buffer-top">
          <table class="table table-striped">
            <tr>
              <td><b>ID</b></td>
              <td><b>Имя</b></td>
              <td><b>Email</b></td>
              <td><b>Число заказов</b></td>
              <td><b>Дата регистрации</b></td>
              <td><b>Управление</b></td>
            </tr>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= user.email %></td>
              <td><%= user.orders.size %></td>
              <td><%= l user.created_at, format: :long %></td>
              <td>
                <%= link_to fa_icon('pencil'), edit_user_path(user), :title => 'Редактировать' %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
    </div>
  </div>
<% else %>
  <p>Здесь может шариться только Admin</p>
<% end %>

app/views/users/show.html.erb
<% if current_user == @user || current_user == User.first %>
  <h1>Пользователь <%= @user.name %></h1>
  <div class="row">
    <div class="col-md-12 buffer-top">
      <p>Почтовый ящик: <b><%= @user.email %></b></p>
      <p>Сделал заказов: <b><%= @user.orders.size %></b></p>
    </div>
  </div>
  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-primary' %>
  </div>
<% else %>
  <p>У Вас нет права здесь находится</p>
<% end %>